name: Publish

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/scriber-pdf
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: uv sync --dev

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
